### ISSUE TITLE
Post-3.0 checklist

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#1145]
- [x] remove link to rc in MustBeAtomic error in ash core
- [x] change links to upgrade guides to be from GitHub to hex packages
- [x] change livebook guides to point to 3.0, not release candidates
- [x] update any relevant links to guides (searching for `3.0.0-rc` should do this)
